version: '3.3'

services:
  postgres:
    image: postgres:15
    container_name: quizarena_postgres
    environment:
      POSTGRES_DB: quizarena
      POSTGRES_USER: quizuser
      POSTGRES_PASSWORD: quizpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/main/resources/sql/init_tables.sql:/docker-entrypoint-initdb.d/init_tables.sql
    restart: unless-stopped

volumes:
  postgres_data:
